name: monai
channels:
    - pytorch
    - defaults
dependencies:
- python>3.6
- ipykernel
- cudatoolkit>=11.3
- pytorch
- torchvision
- matplotlib
- seaborn
- scikit-learn
- pip
- pip:
  - pip
  - monai[all]
  - torchio